const make = (id, question, options, explanation, competency) => ({
  id: `P1-TKP-${String(id).padStart(3, "0")}`,
  category: "TKP",
  question,
  options: options.map(([text, score], index) => ({ id: "ABCDE"[index], text, score })),
  explanation,
  competency,
});

export default [
  make(1, "Seorang warga lanjut usia kesulitan mengisi formulir digital saat antrean sedang panjang. Anda...", [["Memintanya datang bersama keluarga lain hari",2],["Menjelaskan sekilas lalu melayani antrean berikutnya",3],["Mendampingi pengisian secara ringkas sambil menjaga urutan antrean",5],["Mengisikan tanpa menjelaskan apa pun",4],["Menyuruhnya membaca petunjuk sendiri",1]], "Pendampingan yang efisien memberi akses setara tanpa mengabaikan antrean. Mengisikan membantu, tetapi penjelasan tetap penting agar warga mandiri.", "pelayanan publik"),
  make(2, "Anda menerima keluhan keras karena layanan terlambat akibat gangguan sistem. Tindakan Anda...", [["Mendengarkan, meminta maaf, menjelaskan kondisi, dan menawarkan langkah penyelesaian",5],["Menyalahkan bagian teknologi",2],["Meminta warga menunggu tanpa kepastian",3],["Membalas dengan nada tegas agar tenang",1],["Mencatat keluhan dan menjanjikan kabar setelah memperoleh estimasi",4]], "Respons terbaik menggabungkan empati, informasi jujur, dan solusi. Mencatat serta memberi kabar baik, tetapi estimasi perlu diupayakan sejak awal.", "pelayanan publik"),
  make(3, "Rekan kerja meminta Anda melewati verifikasi karena pemohon adalah kenalannya. Anda...", [["Mengikuti karena berkas tampak lengkap",2],["Menolak dan tetap menjalankan verifikasi sesuai prosedur",5],["Meminta rekan menandatangani tanggung jawab",3],["Menunda berkas tanpa penjelasan",1],["Memeriksa melalui jalur normal dan menjelaskan alasannya",4]], "Kepatuhan prosedur dan penjelasan profesional melindungi integritas layanan. Menolak tegas paling tepat bila permintaan jelas melanggar aturan.", "profesionalisme"),
  make(4, "Dua tugas penting memiliki tenggat yang sama. Anda...", [["Mengerjakan yang paling mudah dahulu",2],["Menunggu atasan menentukan semuanya",3],["Memetakan urgensi dan dampak, menyusun waktu, lalu mengomunikasikan risiko",5],["Mengerjakan keduanya bergantian tanpa rencana",4],["Mengabaikan salah satu tugas",1]], "Prioritas berbasis urgensi dan dampak disertai komunikasi risiko merupakan pengelolaan kerja yang paling bertanggung jawab.", "profesionalisme"),
  make(5, "Anda menemukan angka salah pada laporan yang sudah dikirim kepada pimpinan. Anda...", [["Diam karena selisihnya kecil",1],["Memperbaiki file tanpa memberi tahu",3],["Segera melaporkan kesalahan, mengirim koreksi, dan menelusuri penyebabnya",5],["Menunggu jika ada yang bertanya",2],["Mengirim koreksi disertai penjelasan singkat",4]], "Koreksi cepat, transparan, dan disertai perbaikan akar masalah menunjukkan akuntabilitas paling lengkap.", "profesionalisme"),
  make(6, "Anggota baru tim belum memahami alur kerja dan mulai tertinggal. Anda...", [["Membiarkannya belajar sendiri",1],["Mengambil alih seluruh tugasnya",3],["Memberi panduan prioritas, contoh, dan waktu untuk bertanya",5],["Mengeluh kepada ketua tim",2],["Mengirim dokumen panduan tanpa pendampingan",4]], "Panduan terarah dan ruang bertanya mempercepat adaptasi sekaligus menjaga kemandirian anggota baru.", "jejaring kerja"),
  make(7, "Dalam rapat, ide rekan junior diabaikan meski relevan. Anda...", [["Diam agar rapat cepat selesai",2],["Mengulang ide itu tanpa menyebut sumber",1],["Meminta rekan menjelaskan idenya dan mengaitkannya dengan tujuan rapat",5],["Membahasnya setelah rapat",4],["Mengkritik pimpinan rapat secara keras",3]], "Memberi ruang secara langsung dan konstruktif membangun lingkungan kolaboratif. Pembahasan setelah rapat tetap berguna tetapi terlambat memengaruhi keputusan.", "jejaring kerja"),
  make(8, "Tim berbeda pendapat tentang metode pelaksanaan. Anda...", [["Memilih pendapat mayoritas tanpa membahas data",3],["Membandingkan alternatif dengan kriteria tujuan, risiko, dan sumber daya",5],["Mengikuti anggota paling senior",2],["Membiarkan tiap orang memakai metode sendiri",1],["Menguji dua alternatif utama dalam skala kecil",4]], "Perbandingan berbasis kriteria menghasilkan keputusan yang dapat dipertanggungjawabkan. Uji kecil juga baik bila waktu dan sumber daya memungkinkan.", "jejaring kerja"),
  make(9, "Rekan dari unit lain lambat memberikan data yang Anda perlukan. Anda...", [["Mengirim pengingat sopan, menjelaskan tenggat dan dampaknya, lalu menawarkan bantuan",5],["Langsung melapor kepada atasannya",3],["Menunggu tanpa menghubungi",1],["Mengirim pesan keras di grup",2],["Menghubungi secara pribadi untuk memastikan kendala",4]], "Komunikasi jelas mengenai kebutuhan dan dampak, disertai tawaran bantuan, menjaga hubungan kerja sekaligus mendorong penyelesaian.", "jejaring kerja"),
  make(10, "Anda diminta memimpin tim dengan anggota dari berbagai disiplin. Langkah awal Anda...", [["Membagi tugas secara acak",1],["Menentukan semua cara kerja sendiri",2],["Memetakan keahlian, menyepakati tujuan, peran, dan cara koordinasi",5],["Meminta anggota memilih tugas tanpa batas",3],["Menyusun pembagian awal lalu meminta masukan tim",4]], "Pemetaan kompetensi dan kesepakatan kerja menciptakan pembagian peran yang jelas serta rasa memiliki bersama.", "jejaring kerja"),

  make(11, "Rekan membuat candaan yang menyinggung latar budaya anggota lain. Anda...", [["Ikut tertawa agar suasana cair",1],["Diam karena bukan sasaran candaan",2],["Mengingatkan dengan tenang bahwa candaan tersebut tidak pantas dan menjaga ruang kerja inklusif",5],["Mengalihkan topik tanpa penjelasan",3],["Menanyakan kondisi pihak yang tersinggung lalu membahasnya secara pribadi dengan pembuat candaan",4]], "Intervensi tenang yang menghentikan perilaku diskriminatif memberi batas jelas. Pendekatan pribadi baik, tetapi dampak di ruang bersama juga perlu ditangani.", "sosial budaya"),
  make(12, "Warga menggunakan bahasa daerah yang tidak Anda pahami. Anda...", [["Meminta warga pergi mencari penerjemah",1],["Menggunakan bahasa sederhana dan mencari bantuan petugas yang memahami bila diperlukan",5],["Menebak maksud warga",2],["Memberikan formulir tanpa penjelasan",3],["Memakai aplikasi terjemahan sambil mengonfirmasi kembali maksudnya",4]], "Kombinasi bahasa sederhana, bantuan kompeten, dan konfirmasi menjaga akurasi serta akses layanan.", "sosial budaya"),
  make(13, "Jadwal kegiatan tim bertepatan dengan hari besar keagamaan sebagian anggota. Anda...", [["Mempertahankan jadwal tanpa diskusi",1],["Membatalkan seluruh kegiatan",3],["Membahas alternatif jadwal atau pembagian tugas yang tetap memenuhi target",5],["Meminta anggota tersebut menukar sendiri",2],["Menawarkan keikutsertaan daring jika sifat kegiatan memungkinkan",4]], "Akomodasi melalui dialog menjaga target kerja sekaligus menghormati kebutuhan keagamaan tanpa perlakuan diskriminatif.", "sosial budaya"),
  make(14, "Anda ditempatkan di daerah dengan kebiasaan masyarakat yang berbeda. Anda...", [["Memaksakan kebiasaan asal",1],["Mempelajari norma lokal, berkomunikasi dengan tokoh setempat, dan tetap berpegang pada aturan",5],["Menghindari interaksi di luar kantor",2],["Mengikuti semua kebiasaan meski melanggar aturan",3],["Mengamati dan bertanya kepada rekan lokal sebelum bertindak",4]], "Adaptasi terbaik menghormati budaya lokal sambil mempertahankan hukum dan etika pelayanan.", "sosial budaya"),
  make(15, "Dalam seleksi peserta kegiatan, muncul usul membatasi berdasarkan asal daerah. Anda...", [["Menyetujuinya agar peserta seragam",1],["Meminta dasar objektif dan menggunakan kriteria relevan yang berlaku setara",5],["Mengganti batas asal dengan batas usia tanpa kajian",3],["Mengikuti keputusan ketua",2],["Mengusulkan seleksi terbuka dengan kriteria kompetensi",4]], "Kriteria harus berkaitan dengan tujuan kegiatan dan diterapkan setara. Seleksi terbuka berbasis kompetensi merupakan alternatif kuat.", "sosial budaya"),

  make(16, "Anda menerima lampiran email dari alamat mirip pimpinan yang meminta segera dibuka. Anda...", [["Langsung membuka karena mendesak",1],["Meneruskan ke rekan untuk ditanyakan",2],["Memverifikasi alamat dan permintaan melalui kanal resmi serta melaporkan indikasi phishing",5],["Menghapus tanpa melapor",3],["Memindai lampiran dengan perangkat keamanan sebelum tindakan lanjutan",4]], "Verifikasi melalui kanal lain dan pelaporan melindungi organisasi. Pemindaian membantu, tetapi identitas pengirim tetap harus dipastikan.", "teknologi informasi"),
  make(17, "Rekan meminta kata sandi akun Anda untuk menyelesaikan tugas saat Anda cuti. Anda...", [["Memberikannya karena rekan tepercaya",1],["Menolak dan mengatur akses resmi atau delegasi melalui administrator",5],["Mengirim kata sandi lalu menggantinya nanti",2],["Masuk sendiri dari perangkat pribadi dan membiarkan sesi aktif",3],["Membantu mencari mekanisme akun pengganti",4]], "Kredensial pribadi tidak boleh dibagikan. Delegasi resmi menjaga jejak audit dan pembatasan akses.", "teknologi informasi"),
  make(18, "Sistem baru membuat sebagian pegawai kesulitan. Anda yang sudah memahami sistem...", [["Mengerjakan semua tugas mereka",2],["Menyusun panduan singkat dan sesi berbagi berdasarkan kendala utama",5],["Menyuruh mereka membaca manual",3],["Menunggu pelatihan resmi",1],["Membantu kasus mendesak sambil mencatat kebutuhan pelatihan",4]], "Panduan dan berbagi pengetahuan menyelesaikan kebutuhan saat ini sekaligus meningkatkan kapasitas tim secara berkelanjutan.", "teknologi informasi"),
  make(19, "Data pribadi warga terlihat pada layar yang menghadap area umum. Anda...", [["Membiarkan karena hanya sebentar",1],["Mematikan atau mengunci layar dan mengatur posisi serta akses agar tidak terlihat",5],["Menutup sebagian jendela aplikasi",3],["Meminta warga tidak melihat",2],["Segera mengunci layar lalu melaporkan risiko tata letak",4]], "Mengamankan layar dan memperbaiki pengaturan fisik mencegah paparan berulang. Pelaporan risiko juga baik untuk tindak lanjut fasilitas.", "teknologi informasi"),
  make(20, "Anda ingin memakai aplikasi AI publik untuk merangkum dokumen internal. Anda...", [["Mengunggah seluruh dokumen agar hasil lengkap",1],["Menghapus nama file saja",2],["Memeriksa kebijakan, klasifikasi data, dan memakai sarana yang disetujui tanpa data sensitif",5],["Meminta izin rekan terdekat",3],["Menganonimkan data dan berkonsultasi dengan pengelola keamanan",4]], "Penggunaan AI harus mengikuti kebijakan dan klasifikasi informasi. Anonimisasi membantu, tetapi platformnya tetap harus disetujui.", "teknologi informasi"),

  make(21, "Beban kerja meningkat mendadak dan tim mulai kewalahan. Anda...", [["Bekerja tanpa istirahat sampai selesai",3],["Memetakan pekerjaan kritis, membagi ulang tugas, dan melaporkan kebutuhan sumber daya",5],["Mengeluh di media sosial",1],["Menunggu instruksi rinci",2],["Mengajak tim menyusun prioritas harian",4]], "Prioritas, redistribusi, dan eskalasi kebutuhan mengelola tekanan secara sistematis serta melindungi kualitas kerja.", "profesionalisme"),
  make(22, "Atasan memberi instruksi lisan yang berpotensi bertentangan dengan aturan. Anda...", [["Melaksanakan tanpa bertanya",1],["Menolak dengan emosi",2],["Meminta klarifikasi dan dasar aturan, menyampaikan risiko, serta mengusulkan cara yang sah",5],["Menceritakannya kepada semua rekan",3],["Mencatat instruksi dan berkonsultasi melalui jalur yang tepat",4]], "Klarifikasi berbasis aturan dan alternatif yang sah menjaga kepatuhan sekaligus hubungan profesional.", "profesionalisme"),
  make(23, "Hasil kerja Anda dikritik di depan tim. Anda...", [["Membalas kritik saat itu juga",2],["Mendengarkan pokok kritik, meminta contoh konkret, lalu memperbaiki bagian yang valid",5],["Diam tetapi mengabaikannya",1],["Menerima semua kritik tanpa menilai",3],["Mencatat kritik dan membahas rinciannya setelah rapat",4]], "Sikap terbuka sekaligus kritis terhadap umpan balik mempercepat perbaikan. Pembahasan setelah rapat tepat bila suasana tidak mendukung rincian.", "profesionalisme"),
  make(24, "Anda diminta mengerjakan tugas di luar pengalaman utama. Anda...", [["Menolak langsung",1],["Menerima tanpa mencari informasi",2],["Mempelajari kebutuhan, meminta arahan awal, dan menyusun rencana belajar sambil bekerja",5],["Menyerahkan kepada rekan",3],["Mencari contoh pekerjaan dan berkonsultasi dengan orang berpengalaman",4]], "Belajar terarah sambil menjaga koordinasi menunjukkan adaptabilitas dan tanggung jawab terhadap hasil.", "profesionalisme"),
  make(25, "Anda melihat peluang menyederhanakan proses yang berulang. Anda...", [["Mengubah proses sendiri tanpa dokumentasi",2],["Membiarkannya karena proses lama masih berjalan",1],["Mengumpulkan data, merancang perbaikan, menguji terbatas, lalu mengusulkan penerapan",5],["Mengusulkan ide tanpa analisis",3],["Mendiskusikan ide dan membuat purwarupa sederhana",4]], "Perbaikan berbasis data dan uji terbatas mengurangi risiko serta menyediakan bukti manfaat sebelum penerapan luas.", "profesionalisme"),

  make(26, "Di grup kerja beredar ajakan membenci kelompok tertentu. Anda...", [["Diam agar tidak terlibat",2],["Meneruskan kepada teman dekat",1],["Tidak menyebarkan, menyimpan bukti, dan melaporkan melalui mekanisme yang berwenang",5],["Membalas dengan hinaan",3],["Mengingatkan pengirim dan keluar dari percakapan",4]], "Penghentian penyebaran, dokumentasi, dan pelaporan resmi menangani risiko secara bertanggung jawab tanpa memperbesar konflik.", "anti-radikalisme"),
  make(27, "Seorang kenalan mengajak pertemuan tertutup yang menolak dasar negara dan meminta kerahasiaan. Anda...", [["Datang untuk sekadar mendengar",2],["Menolak, menjaga bukti ajakan, dan melaporkan melalui jalur yang tepat",5],["Mengabaikan pesan tanpa tindakan",3],["Menyebarkan identitasnya di media sosial",1],["Menolak dan berkonsultasi dengan atasan atau unit berwenang",4]], "Ajakan yang menolak dasar negara perlu ditolak dan ditangani lewat mekanisme resmi, bukan penghakiman publik.", "anti-radikalisme"),
  make(28, "Dalam diskusi, rekan menyampaikan pandangan politik berbeda tetapi tidak melanggar hukum. Anda...", [["Melabelinya tidak loyal",1],["Menghormati pandangannya dan menjaga diskusi berbasis fakta serta tugas",5],["Menghindarinya selamanya",2],["Meminta ia diam",3],["Mengalihkan diskusi kembali ke tujuan kerja",4]], "Perbedaan pandangan yang sah harus dihormati. Diskusi tetap diarahkan pada fakta dan tanggung jawab profesional.", "anti-radikalisme"),
  make(29, "Anda menemukan materi provokatif pada komputer bersama kantor. Anda...", [["Menghapus lalu diam",3],["Menyebarkannya sebagai peringatan",1],["Mengamankan kondisi tanpa menyebarkan, mencatat temuan, dan melapor kepada pengelola berwenang",5],["Menuduh pengguna terakhir",2],["Memutus koneksi perangkat dan meminta pemeriksaan petugas TI",4]], "Bukti perlu dijaga dan ditangani oleh pihak berwenang. Isolasi perangkat baik, sedangkan tuduhan tanpa pemeriksaan harus dihindari.", "anti-radikalisme"),
  make(30, "Cara terbaik memperkuat ketahanan tim terhadap informasi ekstrem adalah...", [["Melarang seluruh diskusi",1],["Mengadakan literasi digital, ruang dialog, dan kanal pelaporan yang aman",5],["Memantau percakapan pribadi tanpa dasar",2],["Mengirim poster peringatan saja",3],["Membahas studi kasus dan cara verifikasi informasi",4]], "Literasi, dialog, dan pelaporan aman membangun kemampuan pencegahan yang berkelanjutan tanpa menghilangkan kebebasan yang sah.", "anti-radikalisme"),

  make(31, "Pemohon menawarkan hadiah setelah Anda membantunya. Anda...", [["Menerima karena layanan sudah selesai",1],["Menolak dengan sopan dan menjelaskan aturan penerimaan hadiah",5],["Menerima lalu membaginya dengan tim",2],["Menyuruhnya menitipkan kepada orang lain",3],["Menolak dan melaporkan sesuai mekanisme jika termasuk gratifikasi yang wajib dilaporkan",4]], "Penolakan menjaga imparsialitas. Pelaporan diperlukan sesuai karakter dan ketentuan gratifikasi yang berlaku.", "integritas"),
  make(32, "Anda memiliki akses ke data yang tidak terkait tugas saat ini. Anda...", [["Membukanya karena penasaran",1],["Mengakses hanya jika ada kebutuhan tugas dan kewenangan yang sah",5],["Melihat tanpa mengunduh",2],["Meminta izin rekan",3],["Mengonfirmasi kebutuhan akses kepada penanggung jawab data",4]], "Akses data harus berlandaskan kebutuhan dan kewenangan. Sekadar dapat mengakses bukan berarti berhak melihat.", "integritas"),
  make(33, "Rekan meminta Anda mencatat kehadirannya meski ia terlambat. Anda...", [["Membantu sekali ini",1],["Menolak dan mencatat sesuai keadaan sebenarnya",5],["Mencatat hadir tetapi memberi catatan",3],["Tidak menjawab permintaan",2],["Menolak serta mengingatkan mekanisme koreksi resmi",4]], "Catatan harus sesuai fakta. Mekanisme resmi dapat digunakan bila ada alasan yang memang dapat dipertanggungjawabkan.", "integritas"),
  make(34, "Anda mengetahui konflik kepentingan pribadi dalam proses pengadaan yang Anda tangani. Anda...", [["Tetap menangani karena merasa objektif",2],["Mengungkapkan konflik dan mengundurkan diri dari keputusan sesuai prosedur",5],["Meminta pihak terkait merahasiakannya",1],["Membatasi peran tanpa melapor",3],["Berkonsultasi kepada atasan atau unit kepatuhan dan mengikuti arahannya",4]], "Pengungkapan dan pengalihan kewenangan mencegah bias nyata maupun kesan keberpihakan.", "integritas"),
  make(35, "Target kinerja hampir tercapai, tetapi sebagian bukti belum tersedia. Anda...", [["Mengklaim seluruh target",1],["Melaporkan capaian yang dapat dibuktikan dan menjelaskan kekurangan datanya",5],["Memperkirakan bukti yang belum ada",2],["Menunda seluruh laporan",3],["Menyampaikan capaian sementara dengan rencana melengkapi bukti",4]], "Pelaporan harus berdasarkan bukti. Status sementara dapat disampaikan transparan tanpa mengubah fakta.", "integritas"),

  make(36, "Warga memberi saran perbaikan yang belum pernah diterapkan. Anda...", [["Menolaknya karena bukan ahli",1],["Mencatat, menilai manfaat dan kelayakannya, lalu memberi kabar tindak lanjut",5],["Menerima tanpa tindak lanjut",2],["Menyampaikan kepada atasan tanpa telaah",3],["Menguji unsur yang mudah diterapkan dan mendokumentasikan hasil",4]], "Saran publik perlu direspons melalui penilaian dan umpan balik. Uji terbatas baik bila kewenangan dan risikonya sesuai.", "pelayanan publik"),
  make(37, "Antrean layanan meningkat karena satu loket bermasalah. Anda...", [["Menutup layanan sampai loket pulih",1],["Mengalihkan antrean, memberi informasi waktu, dan mengoordinasikan perbaikan",5],["Membiarkan warga memilih loket",2],["Memberi pengumuman tanpa solusi",3],["Membuka bantuan sementara sesuai kewenangan",4]], "Pengalihan, informasi, dan perbaikan menangani kebutuhan warga sekaligus akar gangguan.", "pelayanan publik"),
  make(38, "Pemohon tidak memenuhi satu persyaratan wajib. Anda...", [["Tetap meloloskan karena kasihan",1],["Menolak tanpa penjelasan",2],["Menjelaskan dasar persyaratan dan langkah yang dapat dilakukan untuk melengkapinya",5],["Meminta pemohon mencari bantuan calo",3],["Memberi daftar kekurangan dan kanal konsultasi",4]], "Kepastian prosedur harus disertai penjelasan dan jalan penyelesaian yang jelas, tanpa mengabaikan syarat wajib.", "pelayanan publik"),
  make(39, "Survei menunjukkan warga sulit memahami istilah pada formulir. Anda...", [["Menganggap warga kurang teliti",1],["Mengusulkan bahasa sederhana, menguji pemahaman pengguna, dan memperbarui panduan",5],["Menambah jumlah istilah teknis",2],["Membuat poster tanpa uji",3],["Menambahkan contoh pengisian pada bagian sulit",4]], "Bahasa sederhana dan uji pengguna memastikan perbaikan benar-benar meningkatkan pemahaman, bukan hanya mengubah tampilan.", "pelayanan publik"),
  make(40, "Layanan daring tidak dapat diakses sebagian warga karena keterbatasan perangkat. Anda...", [["Mewajibkan semua warga memakai layanan daring",1],["Menyediakan kanal bantuan atau alternatif yang setara sambil mempertahankan layanan digital",5],["Meminta warga meminjam perangkat",2],["Menghapus layanan daring",3],["Menyediakan petugas pendamping pada waktu tertentu",4]], "Transformasi digital harus tetap inklusif. Kanal bantuan atau alternatif setara mencegah kelompok tertentu kehilangan akses.", "pelayanan publik"),

  make(41, "Anda berbeda pendapat dengan atasan mengenai solusi teknis. Anda...", [["Mengikuti tanpa menyampaikan risiko",2],["Menyampaikan data dan alternatif secara hormat, lalu menjalankan keputusan yang sah",5],["Membantah di depan pihak luar",1],["Menunda pekerjaan",3],["Meminta waktu singkat untuk membandingkan dua opsi",4]], "Perbedaan profesional disampaikan berbasis data dan hormat. Setelah keputusan sah dibuat, tim tetap menjalankannya.", "jejaring kerja"),
  make(42, "Tim Anda berhasil karena bantuan unit lain. Anda...", [["Mengklaim sebagai keberhasilan tim sendiri",1],["Mengakui kontribusi unit lain dalam laporan dan evaluasi",5],["Mengucapkan terima kasih secara pribadi saja",3],["Memberi hadiah pribadi",2],["Mengundang unit tersebut dalam evaluasi bersama",4]], "Pengakuan formal menjaga keadilan kontribusi dan memperkuat kolaborasi; evaluasi bersama juga membangun pembelajaran.", "jejaring kerja"),
  make(43, "Rekan sering memotong pembicaraan anggota lain. Anda sebagai moderator...", [["Membiarkannya karena ia paling senior",1],["Mengingatkan aturan bicara dan memberi giliran secara seimbang",5],["Mematikan mikrofonnya tanpa penjelasan",2],["Menegurnya setelah rapat",3],["Merangkum poinnya lalu mengalihkan giliran kepada anggota lain",4]], "Aturan yang diterapkan setara menjaga partisipasi. Merangkum lalu mengalihkan giliran efektif, meski pengingat aturan lebih jelas untuk semua.", "jejaring kerja"),
  make(44, "Proyek bersama terlambat karena pembagian peran tidak jelas. Anda...", [["Mencari siapa yang salah",1],["Memetakan pekerjaan tersisa, menetapkan penanggung jawab dan tenggat, lalu memantau kemajuan",5],["Mengambil alih semua pekerjaan",2],["Menambah rapat tanpa agenda",3],["Membuat daftar tugas dan meminta konfirmasi pemiliknya",4]], "Kejelasan tugas, penanggung jawab, tenggat, dan pemantauan langsung menangani penyebab keterlambatan.", "jejaring kerja"),
  make(45, "Setelah kegiatan selesai, sebagian anggota ingin langsung berpindah tugas tanpa evaluasi. Anda...", [["Membiarkannya",1],["Mengadakan evaluasi singkat berbasis data, mencatat pelajaran, dan menetapkan tindak lanjut",5],["Menulis evaluasi sendiri",3],["Membahas hanya kesalahan",2],["Mengirim formulir refleksi dan merangkum hasilnya",4]], "Evaluasi singkat yang melibatkan tim, memakai data, dan menghasilkan tindak lanjut mengubah pengalaman menjadi perbaikan nyata.", "jejaring kerja"),
];
