import { Link } from "react-router-dom";
import ThemeToggle from "./components/ThemeToggle";
import logo from "./assets/logo.png";

const features = [
  ["▤", "Latihan bertahap", "Pilih TWK, TIU, TKP, atau latihan campuran dengan mode belajar dan mode ujian."],
  ["◎", "Belajar dari kesalahan", "Jawaban yang belum tepat tersimpan agar dapat kamu pelajari kembali."],
  ["◷", "Analisis hasil", "Lihat nilai per bidang, perkembangan, dan bagian yang perlu ditingkatkan."],
  ["♛", "Tryout terukur", "Kerjakan tryout 110 soal dalam 100 menit dan bandingkan hasil secara sehat."],
];

const faqs = [
  ["Apakah NalarASN merupakan aplikasi resmi pemerintah?", "Bukan. NalarASN adalah platform latihan mandiri yang independen dan tidak berafiliasi dengan BKN atau instansi pemerintah."],
  ["Apakah hasil di NalarASN menjamin kelulusan?", "Tidak. Nilai, peringkat, dan indikator kesiapan hanya digunakan untuk evaluasi latihan, bukan hasil resmi atau jaminan kelulusan."],
  ["Apa perbedaan Latihan dan Tryout?", "Latihan membantu memahami materi secara bertahap. Tryout mensimulasikan sesi ujian lengkap dengan waktu, nilai, dan peringkat."],
  ["Apakah ada akses gratis?", "Ya. Latihan dasar, Tryout 1, dan agenda Tryout Nasional tertentu dapat digunakan gratis sesuai ketentuan yang ditampilkan."],
  ["Kapan paket premium dibuka?", "Paket premium akan dibuka setelah sistem pembayaran dan administrasi layanan siap. Selama mode beta, paket tersebut ditandai Segera Hadir."],
];

export default function LandingPageSKDCore() {
  return <div className="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-50">
    <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/90 backdrop-blur dark:border-slate-800 dark:bg-slate-900/90"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4"><Link to="/" className="rounded-lg bg-white p-1.5"><img src={logo} alt="NalarASN" className="h-9 w-auto max-w-[150px] object-contain" /></Link><nav className="hidden items-center gap-6 text-sm font-semibold text-slate-600 dark:text-slate-300 md:flex"><a href="#fitur">Fitur</a><a href="#cara-kerja">Cara kerja</a><a href="#faq">FAQ</a></nav><div className="flex items-center gap-2"><ThemeToggle/><Link to="/login" className="rounded-xl border border-blue-200 px-4 py-2 text-sm font-semibold text-blue-700 dark:border-blue-900 dark:text-blue-300">Masuk</Link><Link to="/register" className="hidden rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white sm:block">Daftar gratis</Link></div></div></header>
    <main>
      <section className="mx-auto grid max-w-6xl items-center gap-10 px-4 py-14 md:grid-cols-2 md:py-24"><div><span className="inline-flex rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700 dark:bg-blue-950/40 dark:text-blue-300">Platform latihan SKD berbasis perkembangan</span><h1 className="mt-5 text-4xl font-black leading-tight md:text-6xl">Bukan sekadar hafal, tapi paham cara <span className="text-blue-600">bernalar.</span></h1><p className="mt-5 max-w-xl text-base leading-8 text-slate-600 dark:text-slate-300">NalarASN membantu kamu berlatih, mengenali kelemahan, dan menentukan apa yang perlu dipelajari selanjutnya.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/register" className="rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white shadow-lg shadow-blue-600/20">Mulai gratis</Link><a href="#cara-kerja" className="rounded-xl border border-slate-300 bg-white px-6 py-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-900">Lihat cara kerja</a></div><p className="mt-4 text-xs text-slate-500">Independen dan tidak berafiliasi dengan BKN atau instansi pemerintah.</p></div>
        <div className="rounded-[2rem] border border-blue-100 bg-gradient-to-br from-blue-700 to-cyan-500 p-5 text-white shadow-2xl shadow-blue-600/20 sm:p-8"><p className="text-xs font-bold uppercase tracking-wider text-blue-100">Rencana latihanmu</p><h2 className="mt-2 text-2xl font-bold">Fokus minggu ini: TIU</h2><p className="mt-2 text-sm leading-6 text-blue-100">Kemampuan numerik meningkat. Perkuat silogisme dan manajemen waktu.</p><div className="mt-6 grid grid-cols-3 gap-2">{[["TWK","72%"],["TIU","61%"],["TKP","78%"]].map(([label,value])=><div key={label} className="rounded-2xl bg-white/15 p-3"><small className="text-blue-100">{label}</small><strong className="mt-1 block text-xl">{value}</strong></div>)}</div><div className="mt-4 rounded-2xl bg-white p-4 text-slate-900"><small className="font-bold text-blue-600">MISI HARI INI</small><p className="mt-1 text-sm font-semibold">Selesaikan 5 soal penalaran dalam 7 menit.</p></div></div>
      </section>
      <section id="fitur" className="border-y border-slate-200 bg-white py-16 dark:border-slate-800 dark:bg-slate-900"><div className="mx-auto max-w-6xl px-4"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Mengapa NalarASN</p><h2 className="mt-2 text-3xl font-bold">Latihan yang memberi arah</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([icon,title,description])=><article key={title} className="rounded-2xl border border-slate-200 p-5 dark:border-slate-800"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-xl text-blue-700 dark:bg-blue-950/40 dark:text-blue-300">{icon}</span><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></article>)}</div></div></section>
      <section id="cara-kerja" className="mx-auto max-w-6xl px-4 py-16"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Cara kerja</p><h2 className="mt-2 text-3xl font-bold">Tiga langkah untuk berkembang</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{[["01","Pilih latihan","Mulai dari bidang yang ingin kamu kuasai atau ikuti tryout untuk mengukur kemampuan."],["02","Pelajari hasil","Lihat jawaban yang belum tepat, pembahasan, dan bidang yang masih perlu diperkuat."],["03","Latihan terarah","Gunakan Buku Kesalahan dan rekomendasi latihan agar kemajuanmu dapat terlihat."]].map(([number,title,description])=><article key={number} className="rounded-2xl bg-slate-100 p-6 dark:bg-slate-900"><span className="text-sm font-black text-blue-600">{number}</span><h3 className="mt-6 text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></article>)}</div></section>
      <section id="faq" className="bg-slate-100 py-16 dark:bg-slate-900/60"><div className="mx-auto max-w-4xl px-4"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">FAQ</p><h2 className="mt-2 text-3xl font-bold">Pertanyaan yang sering ditanyakan</h2><div className="mt-8 space-y-3">{faqs.map(([question,answer])=><details key={question} className="group rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><summary className="cursor-pointer list-none pr-6 font-bold">{question}<span className="float-right text-blue-600 group-open:rotate-45">+</span></summary><p className="mt-3 text-sm leading-6 text-slate-500">{answer}</p></details>)}</div></div></section>
    </main>
    <footer className="border-t border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950"><div className="mx-auto grid max-w-6xl gap-6 px-4 py-8 text-sm sm:grid-cols-[1fr_auto]"><div><div className="inline-block rounded-lg bg-white p-1.5"><img src={logo} alt="NalarASN" className="h-8 w-auto object-contain" /></div><p className="mt-2 max-w-md text-xs leading-5 text-slate-500">Platform latihan mandiri. Nilai pada aplikasi bukan hasil resmi dan tidak menjamin kelulusan.</p></div><div className="flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-slate-600 dark:text-slate-300"><Link to="/panduan">Panduan</Link><Link to="/privasi">Privasi</Link><Link to="/ketentuan">Ketentuan</Link></div><p className="text-xs text-slate-500 sm:col-span-2">© {new Date().getFullYear()} NalarASN. Bukan layanan resmi pemerintah.</p></div></footer>
  </div>;
}
